GreptimeTeam/greptimedb-ingester-java

.github/workflows/build.yml, .github/workflows/mvn_publish.yml, ingester-example/src/main/java/io/greptime/QuickStart.java, ingester-protocol/src/main/java/io/greptime/GreptimeDB.java, ingester-protocol/src/main/java/io/greptime/PojoMapper.java, ingester-protocol/src/test/java/io/greptime/PojoMapperTest.java
=> feat: add workflows

ingester-protocol/src/main/java/io/greptime/GreptimeDB.java, ingester-protocol/src/main/java/io/greptime/Status.java, ingester-protocol/src/main/java/io/greptime/Write.java, ingester-protocol/src/main/java/io/greptime/WriteClient.java, ingester-protocol/src/main/java/io/greptime/WriteOp.java, ingester-protocol/src/main/java/io/greptime/WritePOJO.java, ingester-protocol/src/main/java/io/greptime/models/TableRows.java, ingester-protocol/src/main/java/io/greptime/models/TableRowsHelper.java, ingester-protocol/src/main/java/io/greptime/models/WriteTable.java, ingester-protocol/src/test/java/io/greptime/models/TableRowsTest.java
=> feat: support delete

ingester-protocol/pom.xml, ingester-protocol/src/main/java/io/greptime/WriteClient.java
=> feat: upgrade proto to 0.4.3

ingester-all/pom.xml, ingester-common/pom.xml, ingester-example/pom.xml, ingester-grpc/pom.xml, ingester-protocol/pom.xml, ingester-protocol/src/main/resources/client_version.properties, ingester-protocol/src/test/java/io/greptime/UtilTest.java, ingester-rpc/pom.xml, pom.xml
=> release: v0.7.0

ingester-protocol/pom.xml
=> feat: upgrade proto to 0.7.0

ingester-all/pom.xml, ingester-common/pom.xml, ingester-example/pom.xml, ingester-grpc/pom.xml, ingester-protocol/pom.xml, ingester-protocol/src/main/resources/client_version.properties, ingester-protocol/src/test/java/io/greptime/UtilTest.java, ingester-rpc/pom.xml, pom.xml
Align with the DB version: https://github.com/GreptimeTeam/greptimedb/releases/tag/v0.9.1
=> release: 0.9.1

.github/workflows/mvn_publish.yml
=> chore: use token to publishing

pom.xml
=> chore: remove gpg plugin

.github/workflows/mvn_publish.yml, pom.xml
=> feat: gpg please reback

ingester-all/pom.xml, ingester-common/pom.xml, ingester-example/pom.xml, ingester-grpc/pom.xml, ingester-protocol/pom.xml, ingester-protocol/src/main/resources/client_version.properties, ingester-protocol/src/test/java/io/greptime/UtilTest.java, ingester-rpc/pom.xml, pom.xml
=> release: v0.11.0

ingester-rpc/src/main/java/io/greptime/rpc/Context.java, ingester-rpc/src/test/java/io/greptime/rpc/ContextTest.java
=> feat: new hints

ingester-example/src/main/java/io/greptime/LowLevelApiStreamWriteQuickStart.java, ingester-grpc/pom.xml, ingester-grpc/src/main/java/io/greptime/rpc/GrpcClient.java, ingester-grpc/src/main/java/io/greptime/rpc/ZstdCodec.java, ingester-rpc/src/main/java/io/greptime/rpc/Compression.java, ingester-rpc/src/main/java/io/greptime/rpc/Context.java
=> feat: zstd codec

ingester-all/pom.xml, ingester-common/pom.xml, ingester-example/pom.xml, ingester-grpc/pom.xml, ingester-protocol/pom.xml, ingester-protocol/src/main/resources/client_version.properties, ingester-protocol/src/test/java/io/greptime/UtilTest.java, ingester-rpc/pom.xml, pom.xml
=> release: v0.12.1

ingester-common/src/main/java/io/greptime/common/Lifecycle.java, ingester-common/src/main/java/io/greptime/common/signal/SignalHelper.java, ingester-common/src/main/java/io/greptime/common/util/DirectExecutor.java, ingester-common/src/main/java/io/greptime/common/util/MetricReporter.java, ingester-common/src/main/java/io/greptime/common/util/NamedThreadFactory.java, ingester-common/src/main/java/io/greptime/common/util/Platform.java, ingester-common/src/main/java/io/greptime/common/util/ServiceLoader.java, ingester-common/src/main/java/io/greptime/common/util/SystemPropertyUtil.java, ingester-example/src/main/java/io/greptime/HighLevelApiStreamWriteQuickStart.java, ingester-example/src/main/java/io/greptime/HighLevelApiWriteQuickStart.java, ingester-example/src/main/java/io/greptime/LowLevelApiStreamWriteQuickStart.java, ingester-example/src/main/java/io/greptime/LowLevelApiWriteQuickStart.java, ingester-grpc/src/main/java/io/greptime/rpc/interceptors/ClientRequestLimitInterceptor.java, ingester-grpc/src/main/java/io/greptime/rpc/limit/Gradient2Limit.java, ingester-grpc/src/main/java/io/greptime/rpc/limit/VegasLimit.java, ingester-grpc/src/test/java/io/greptime/rpc/ZstdCodecTest.java, ingester-protocol/src/main/java/io/greptime/CachedPojoObjectMapper.java, ingester-protocol/src/main/java/io/greptime/RouterClient.java, ingester-protocol/src/main/java/io/greptime/WriteClient.java, ingester-protocol/src/main/java/io/greptime/errors/PojoException.java, ingester-protocol/src/main/java/io/greptime/errors/ServerException.java, ingester-protocol/src/main/java/io/greptime/errors/StreamException.java, ingester-protocol/src/main/java/io/greptime/models/Result.java, ingester-protocol/src/main/java/io/greptime/models/Table.java, ingester-protocol/src/main/java/io/greptime/models/TableSchema.java, ingester-protocol/src/test/java/io/greptime/models/TableTest.java, ingester-protocol/src/test/java/io/greptime/models/ValueUtilTest.java, ingester-rpc/src/main/java/io/greptime/rpc/RpcClient.java, ingester-rpc/src/main/java/io/greptime/rpc/RpcFactory.java, ingester-rpc/src/main/java/io/greptime/rpc/RpcOptions.java
Optimize some doc, especially the quick start demo and content related to `Table` and `TableSchema`.
=> chore: minor refactor 20250312

ingester-all/pom.xml, ingester-common/pom.xml, ingester-example/pom.xml, ingester-grpc/pom.xml, ingester-protocol/pom.xml, ingester-protocol/src/main/resources/client_version.properties, ingester-protocol/src/test/java/io/greptime/UtilTest.java, ingester-rpc/pom.xml, pom.xml
=> release: v0.12.2

ingester-bulk-protocol/pom.xml, ingester-bulk-protocol/src/main/java/io/greptime/ArrowCompressionType.java, ingester-bulk-protocol/src/main/java/io/greptime/BulkWriteManager.java, ingester-bulk-protocol/src/main/java/org/apache/arrow/flight/BulkFlightClient.java, ingester-example/src/main/java/io/greptime/BulkWriteApiQuickStart.java, ingester-example/src/main/java/io/greptime/TestConnector.java, ingester-protocol/src/main/java/io/greptime/BulkStreamWriter.java, ingester-protocol/src/main/java/io/greptime/BulkWriteClient.java, ingester-protocol/src/main/java/io/greptime/options/GreptimeOptions.java
=> feat: zstd compression in arrow IPC

.github/workflows/mvn_publish.yml, pom.xml
=> chore: mvn release

README.md, ingester-example/README.md
=> docs: update readme

ingester-all/pom.xml, ingester-bulk-protocol/pom.xml, ingester-common/pom.xml, ingester-example/pom.xml, ingester-grpc/pom.xml, ingester-prometheus-metrics/pom.xml, ingester-protocol/pom.xml, ingester-protocol/src/main/resources/client_version.properties, ingester-protocol/src/test/java/io/greptime/UtilTest.java, ingester-rpc/pom.xml, pom.xml
=> release: v0.14.3

ingester-all/pom.xml, ingester-bulk-protocol/pom.xml, ingester-common/pom.xml, ingester-example/pom.xml, ingester-grpc/pom.xml, ingester-prometheus-metrics/pom.xml, ingester-protocol/pom.xml, ingester-protocol/src/main/resources/client_version.properties, ingester-protocol/src/test/java/io/greptime/UtilTest.java, ingester-rpc/pom.xml, pom.xml
=> release: v0.14.4
