ingester-example/src/main/java/io/greptime/StreamWriteQuickStart.java
ingester-example/src/main/java/io/greptime/WriteQuickStart.java
ingester-protocol/src/main/java/io/greptime/GreptimeDB.java
ingester-protocol/src/main/java/io/greptime/PojoMapper.java
ingester-protocol/src/main/java/io/greptime/Write.java
ingester-protocol/src/main/java/io/greptime/WriteClient.java
ingester-protocol/src/main/java/io/greptime/limit/WriteLimiter.java
ingester-protocol/src/main/java/io/greptime/models/Column.java
ingester-protocol/src/main/java/io/greptime/models/Err.java
ingester-protocol/src/main/java/io/greptime/models/Metric.java
ingester-protocol/src/main/java/io/greptime/models/Table.java
ingester-protocol/src/main/java/io/greptime/models/TableHelper.java
ingester-protocol/src/main/java/io/greptime/models/WriteTable.java
ingester-protocol/src/test/java/io/greptime/PojoMapperTest.java
ingester-protocol/src/test/java/io/greptime/TestUtil.java
ingester-protocol/src/test/java/io/greptime/WriteClientTest.java
ingester-protocol/src/test/java/io/greptime/WriteLimitTest.java
ingester-protocol/src/test/java/io/greptime/models/TableTest.java

API refactor:
```
TableRows -> Table
TableRows.insert(..) -> Table.addRow(..)
```

refactor: refactor API

---

ingester-protocol/src/main/java/io/greptime/models/Util.java
ingester-protocol/src/test/java/io/greptime/models/UtilTest.java

Because the db change the `DateTime` from [seconds to millis](https://github.com/GreptimeTeam/greptimedb/commit/54e506a4940d01ffd3f2e44e450ab6e8cca35481#diff-2f52fff389d90de1f91c0d66b9c7d9e6a48d25beb2c1dfb9ee6dcff2aba4d245L27)

fix: datatime millis

---

ingester-example/src/main/java/io/greptime/StreamWriteQuickStart.java
ingester-example/src/main/java/io/greptime/WritePOJOsQuickStart.java
ingester-example/src/main/java/io/greptime/WriteQuickStart.java
ingester-protocol/src/main/java/io/greptime/models/DataType.java
ingester-protocol/src/main/java/io/greptime/models/RowHelper.java
ingester-protocol/src/main/java/io/greptime/models/TableSchema.java
ingester-protocol/src/test/java/io/greptime/PojoMapperTest.java
ingester-protocol/src/test/java/io/greptime/TestUtil.java
ingester-protocol/src/test/java/io/greptime/WriteClientTest.java
ingester-protocol/src/test/java/io/greptime/WriteLimitTest.java
ingester-protocol/src/test/java/io/greptime/models/ResultTest.java
ingester-protocol/src/test/java/io/greptime/models/TableSchemaTest.java
ingester-protocol/src/test/java/io/greptime/models/TableTest.java
ingester-protocol/src/test/java/io/greptime/options/GreptimeOptionsTest.java

feat: friendly api for table schema

---

ingester-example/src/main/java/io/greptime/TestConnector.java
ingester-protocol/src/main/java/io/greptime/WriteClient.java
ingester-protocol/src/main/java/io/greptime/options/GreptimeOptions.java
ingester-protocol/src/main/java/io/greptime/options/WriteOptions.java
ingester-protocol/src/test/java/io/greptime/options/GreptimeOptionsTest.java

The point-based rate limiter is used in `stream write`, while the row-based rate limiter is used in `write`. This is somewhat fragmented. Now we will unify the use of the point-based rate limiter.

feat: max inflight write points limiter

---

ingester-example/src/main/java/io/greptime/TestConnector.java
ingester-grpc/src/main/java/io/greptime/rpc/GrpcClient.java
ingester-protocol/src/main/java/io/greptime/options/GreptimeOptions.java
ingester-rpc/src/main/java/io/greptime/rpc/RpcOptions.java
ingester-rpc/src/main/java/io/greptime/rpc/TlsOptions.java

this patch add `TlsOption` that allows user to connect to a tls protected grpc port.
This option can be configured via `GreptimeOption` builder. It also contains optional certficate and trust root when the server hosts self-signed certificate.

feat: add option to connect to secure grpc port

---

ingester-rpc/pom.xml
ingester-rpc/src/main/java/io/greptime/rpc/Context.java
ingester-rpc/src/test/java/io/greptime/rpc/ContextTest.java

https://github.com/GreptimeTeam/greptimedb/pull/4454#issuecomment-2256410922

feat: add hint api for Context

---

ingester-protocol/src/main/java/io/greptime/GreptimeDB.java
ingester-protocol/src/main/java/io/greptime/Health.java
ingester-protocol/src/main/java/io/greptime/HealthCheck.java
ingester-protocol/src/main/java/io/greptime/Router.java
ingester-protocol/src/main/java/io/greptime/RouterClient.java
ingester-protocol/src/main/java/io/greptime/RpcServiceRegister.java
ingester-protocol/src/main/java/io/greptime/Util.java
ingester-protocol/src/main/java/io/greptime/WriteClient.java
ingester-protocol/src/main/java/io/greptime/options/GreptimeOptions.java
ingester-protocol/src/test/java/io/greptime/options/GreptimeOptionsTest.java

feat: health check

---

ingester-protocol/pom.xml
ingester-protocol/src/main/java/io/greptime/models/DataType.java
ingester-protocol/src/main/java/io/greptime/models/RowHelper.java
ingester-protocol/src/test/java/io/greptime/WriteClientTest.java

Waiting for: 
https://github.com/GreptimeTeam/greptimedb/pull/4908

feat: json type support

---

ingester-protocol/src/main/java/io/greptime/Status.java

chore: update status code

---

ingester-grpc/pom.xml
ingester-protocol/pom.xml
ingester-protocol/src/main/java/io/greptime/models/RowHelper.java
ingester-protocol/src/main/java/io/greptime/models/ValueUtil.java
ingester-protocol/src/test/java/io/greptime/WriteClientTest.java
ingester-protocol/src/test/java/io/greptime/models/ValueUtilTest.java
pom.xml

feat: support write json object

---

ingester-protocol/src/main/java/io/greptime/models/DataType.java
ingester-protocol/src/main/java/io/greptime/models/RowHelper.java
ingester-protocol/src/main/java/io/greptime/models/ValueUtil.java
ingester-protocol/src/test/java/io/greptime/WriteClientTest.java
ingester-protocol/src/test/java/io/greptime/models/ValueUtilTest.java

1. Remove all `Interval` data types; for details, see https://github.com/GreptimeTeam/greptimedb/issues/5489.
2. Make `DateTime` an alias of timestamp(6); for details, see https://github.com/GreptimeTeam/greptimedb/pull/5422.
3. Minor user experience improvement: allow direct use of the Instant type to write into the Timestamp column.

feat: remove interval type and give datetime an alias

---

ingester-common/src/main/java/io/greptime/common/SPI.java
ingester-example/src/main/java/io/greptime/BulkWriteApiQuickStart.java
ingester-example/src/main/java/io/greptime/bench/BulkWriteBenchmark.java
ingester-example/src/main/java/io/greptime/bench/DBConnector.java
ingester-example/src/main/java/io/greptime/bench/RandomTableDataProvider.java
ingester-example/src/main/java/io/greptime/bench/StreamingWriteBenchmark.java
ingester-example/src/main/java/io/greptime/bench/TableDataProvider.java
ingester-example/src/main/resources/META-INF/services/io.greptime.bench.TableDataProvider

feat: simple bench for writing

---

ingester-all/pom.xml
ingester-bulk-protocol/pom.xml
ingester-bulk-protocol/src/main/java/io/greptime/BulkWriteManager.java
ingester-bulk-protocol/src/main/java/io/greptime/BulkWriteService.java
ingester-bulk-protocol/src/main/java/org/apache/arrow/flight/BulkFlightClient.java
ingester-common/pom.xml
ingester-example/pom.xml
ingester-example/src/main/java/io/greptime/BulkWriteApiQuickStart.java
ingester-example/src/main/java/io/greptime/bench/BulkWriteBenchmark.java
ingester-example/src/main/java/io/greptime/bench/LogTextHelper.java
ingester-example/src/main/java/io/greptime/bench/MultiProducerTableDataProvider.java
ingester-example/src/main/java/io/greptime/bench/RandomTableDataProvider.java
ingester-example/src/main/java/io/greptime/bench/StreamingWriteBenchmark.java
ingester-example/src/main/resources/META-INF/services/io.greptime.bench.TableDataProvider
ingester-grpc/pom.xml
ingester-protocol/pom.xml
ingester-protocol/src/main/java/io/greptime/BulkStreamWriter.java
ingester-protocol/src/main/java/io/greptime/BulkWrite.java
ingester-protocol/src/main/java/io/greptime/BulkWriteClient.java
ingester-protocol/src/main/java/io/greptime/models/ArrowHelper.java
ingester-protocol/src/main/java/io/greptime/models/RowHelper.java
ingester-protocol/src/main/java/io/greptime/models/Table.java
ingester-protocol/src/main/java/io/greptime/models/TableSchema.java
ingester-protocol/src/main/java/io/greptime/models/ValueUtil.java
ingester-protocol/src/main/resources/client_version.properties
ingester-protocol/src/test/java/io/greptime/UtilTest.java
ingester-protocol/src/test/java/io/greptime/models/ArrowHelperTest.java
ingester-rpc/pom.xml
pom.xml

1. Enhance the bulk write pipeline.
2. Add a new bench data provider, `MultiProducerTableDataProvider`, to accelerate data generation.
3. Map json type from arrow utf8 to arrow binary

feat: real pipeline for bulk write

---

ingester-example/README.md

feat: readme for example module

---

ingester-example/src/main/java/io/greptime/BulkWriteApiQuickStart.java
ingester-example/src/main/java/io/greptime/bench/BulkWriteBenchmark.java
ingester-example/src/main/java/io/greptime/bench/StreamingWriteBenchmark.java
ingester-prometheus-metrics/pom.xml
ingester-prometheus-metrics/src/main/java/io/greptime/metrics/MetricsExporter.java
pom.xml

feat: prometheus metrics exporter

---

README.md
ingester-example/src/main/java/io/greptime/bench/BatchingWriteBenchmark.java
ingester-example/src/main/java/io/greptime/bench/BulkWriteBenchmark.java
ingester-example/src/main/java/io/greptime/bench/StreamingWriteBenchmark.java
ingester-prometheus-metrics/README.md
ingester-prometheus-metrics/src/main/java/io/greptime/metrics/ExporterOptions.java
ingester-prometheus-metrics/src/main/java/io/greptime/metrics/MetricsExporter.java

1. minor refactor of `metrics` module
2. add readme.md

feat: add readme for metrics module

---

ingester-all/pom.xml
ingester-bulk-protocol/pom.xml
ingester-common/pom.xml
ingester-example/pom.xml
ingester-grpc/pom.xml
ingester-prometheus-metrics/README.md
ingester-prometheus-metrics/pom.xml
ingester-prometheus-metrics/src/main/java/io/greptime/metrics/ExporterOptions.java
ingester-prometheus-metrics/src/main/java/io/greptime/metrics/MetricsExporter.java
ingester-protocol/pom.xml
ingester-protocol/src/main/resources/client_version.properties
ingester-protocol/src/test/java/io/greptime/UtilTest.java
ingester-rpc/pom.xml
pom.xml

release: v0.14.5

---

README.md
ingester-example/README.md
ingester-example/src/main/java/io/greptime/bench/DBConnector.java
ingester-example/src/main/java/io/greptime/bench/benchmark/BatchingWriteBenchmark.java
ingester-example/src/main/java/io/greptime/bench/benchmark/BulkWriteBenchmark.java
ingester-example/src/main/java/io/greptime/bench/benchmark/StreamingWriteBenchmark.java
ingester-example/src/main/java/io/greptime/metric/Cpu.java
ingester-example/src/main/java/io/greptime/metric/Memory.java
ingester-example/src/main/java/io/greptime/quickstart/TestConnector.java
ingester-example/src/main/java/io/greptime/quickstart/query/QueryJDBCQuickStart.java
ingester-example/src/main/java/io/greptime/quickstart/write/BulkWriteApiQuickStart.java
ingester-example/src/main/java/io/greptime/quickstart/write/HighLevelApiStreamWriteQuickStart.java
ingester-example/src/main/java/io/greptime/quickstart/write/HighLevelApiWriteQuickStart.java
ingester-example/src/main/java/io/greptime/quickstart/write/LowLevelApiStreamWriteQuickStart.java
ingester-example/src/main/java/io/greptime/quickstart/write/LowLevelApiWriteQuickStart.java
ingester-example/src/main/resources/db-connection.properties
ingester-prometheus-metrics/src/main/java/io/greptime/metrics/ExporterOptions.java
ingester-prometheus-metrics/src/main/java/io/greptime/metrics/MetricsExporter.java

- Rename packages to better reflect their purpose (e.g., quickstart, benchmark).
- Move database connection logic to a central DBConnector class.
- Use properties file for database connection details.
- fix deamon to daemon.

[refactor](ingester-example): reorganize project structure and improve database connection configuration.

---

ingester-all/pom.xml
ingester-bulk-protocol/pom.xml
ingester-common/pom.xml
ingester-example/README.md
ingester-example/pom.xml
ingester-example/src/main/java/io/greptime/bench/DBConnector.java
ingester-example/src/main/java/io/greptime/bench/benchmark/BatchingWriteBenchmark.java
ingester-grpc/pom.xml
ingester-prometheus-metrics/pom.xml
ingester-protocol/pom.xml
ingester-protocol/src/main/resources/client_version.properties
ingester-protocol/src/test/java/io/greptime/UtilTest.java
ingester-rpc/pom.xml
pom.xml

A new version needs to be released because #86 includes a fix for `ExporterOptions`.

release: v0.14.6

---

ingester-rpc/src/main/java/io/greptime/rpc/RpcOptions.java

Sometimes users write very large amounts of data, causing the response to slow down.

chore: default rpc timeout to 60s
